- exe/retest
- lib/retest.rb
- lib/retest/command.rb
- test/retest/command_test.rb
> Cache file after first run

- lib/retest/command.rb
- test/retest/command_test.rb
> WIP - cache the latest test file run

- lib/retest/repository.rb
- test/retest/repository/multiple_test_files_with_user_input.rb
- test/retest/repository_test.rb
> Fix reverse list bug

- lib/retest/command.rb
- lib/retest/repository.rb
- test/retest/command_test.rb
- test/retest/repository_test.rb
> Return file changed when is test

- exe/retest
- lib/retest.rb
- lib/retest/listen_options.rb
- test/retest/listen_options_test.rb
> ignore git files

- Gemfile.lock
- exe/retest
- features/retest_flags.feature
- features/support/test_helper.rb
- lib/retest.rb
- lib/retest/options.rb
- lib/retest/runner.rb
- retest.gemspec
- test/fixtures/files/ruby/file.rb
- test/fixtures/files/ruby/file_test.rb
- test/retest/options_test.rb
- test/retest/runner_test.rb
Fixes #29
Fixes #30
Fixes #33 
Fixes #34
> Create CLI options

- exe/retest
- features/retest.feature
- features/retest_help.feature
- features/support/steps.rb
- lib/retest/options.rb
- test/retest/options/help.txt
- test/retest/options_test.rb
> Print help

- features/retest_flags.feature
- features/support/steps.rb
- lib/retest/options.rb
- test/retest/options/help.txt
- test/retest/options_test.rb
> Create -all Flag 

- lib/retest/version_control.rb
> Issue - Watch untracked files

- bin/test/hanami-app
- bin/test/rails-app
- bin/test/ruby-app
- exe/retest
- features/ruby-app/retest/retest_test/flags_test.rb
> Issue - Printing help in docker 

- bin/debug
- bin/test/hanami-app
- features/hanami-app/retest/retest_test.rb
- features/hanami-app/retest/test_helper.rb
- features/rails-app/retest/retest_test.rb
- features/rails-app/retest/test_helper.rb
- features/rspec-rails/retest/retest_test.rb
- features/rspec-rails/retest/test_helper.rb
- features/rspec-ruby/retest/retest_test.rb
- features/rspec-ruby/retest/retest_test/flags_test.rb
- features/rspec-ruby/retest/retest_test/setup_test.rb
- features/rspec-ruby/retest/test_helper.rb
- features/ruby-app/retest/retest_test.rb
- features/ruby-app/retest/retest_test/flags_test.rb
- features/ruby-app/retest/retest_test/setup_test.rb
- features/ruby-app/retest/test_helper.rb
- lib/retest.rb
- lib/retest/options.rb
- lib/retest/repository.rb
- lib/retest/setup.rb
- test/retest/options/auto_flag.rb
- test/retest/options/help.txt
- test/retest/options_test.rb
- test/retest/repository_test.rb
- test/retest/setup_test.rb
Fixes #31
This PR introduces Retest::Setup class to identify which Ruby setup the repository runs on
> Feature - Auto flag

- features/ruby-app/retest/retest_test.rb
- features/ruby-app/retest/retest_test/matching_unmatching_command_test.rb
- lib/retest.rb
- lib/retest/runner.rb
- test/retest/runner_test.rb
> Prevent finding a test on unmatching command (HardcodedCommand)

- lib/retest/setup.rb
> Check Gemfile.lock instead of Gemfile to identify ruby setup

- .github/workflows/ci.yml
- bin/test/ruby-bare
- features/ruby-bare/.gitignore
- features/ruby-bare/Dockerfile
- features/ruby-bare/docker-compose.yml
- features/ruby-bare/program.rb
- features/ruby-bare/program_test.rb
- features/ruby-bare/retest/retest_test.rb
- features/ruby-bare/retest/support/output_file.rb
- features/ruby-bare/retest/test_helper.rb
- lib/retest.rb
- lib/retest/command/rails.rb
- lib/retest/command/rake.rb
- lib/retest/command/rspec.rb
- lib/retest/command/ruby.rb
- lib/retest/file_system.rb
- test/retest/command/setup_commands.rb
- test/retest/file_system_test.rb
- test/test_helper.rb
> Issue - Handle ruby projects without a Gemfile

- features/ruby-bare/retest/scenarios/changed_and_test_placeholders.rb
- features/ruby-bare/retest/scenarios/multiple_commands.rb
- lib/retest/runners/variable_runner.rb
- test/retest/runners/variable_runner_test.rb
> Fix paceholder copy

- features/hanami-app/retest/retest_test.rb
- features/rails-app/retest/retest_test.rb
- features/rspec-rails/retest/retest_test.rb
- lib/retest/command.rb
- lib/retest/options.rb
- test/retest/command/auto_flag.rb
- test/retest/command_test.rb
- test/retest/options/help.txt
- test/retest/options_test.rb
Fixes #117
- Remove --auto option
- Update feature specs
> Delete --auto option

- exe/retest
- features/ruby-bare/retest/scenarios/force_polling.rb
- lib/retest.rb
- lib/retest/options.rb
- lib/retest/program.rb
- test/retest/options/help.txt
- test/retest/options_test.rb
- test/retest/program_test.rb
- test/retest_test.rb
> Feature - Add polling flag

- exe/retest
- features/ruby-bare/Dockerfile
- features/ruby-bare/retest/retest_test.rb
- features/ruby-bare/retest/scenarios/interruptions.rb
> Feature - Handle Interrupt Signal

- lib/retest/program.rb
> Fix - Fix Diff command

- features/rspec-ruby/retest/retest_test/file_changes_test.rb
- lib/retest/matching_options.rb
- lib/retest/matching_options/path.rb
- test/retest/matching_options/path_test.rb
- test/retest/matching_options_test.rb
> Fix default matching pattern

- .github/dependabot.yml
> Add depdendabot.yml configuration file

- exe/retest
- lib/retest/prompt.rb
- lib/retest/sounds.rb
- test/retest/prompt_test.rb
- test/retest/sounds/mac_os_test.rb
> Add sound observer to prompt

- exe/retest
- features/ruby-bare/retest/flags/version.rb
- features/ruby-bare/retest/retest_test.rb
- lib/retest/options.rb
- test/retest/options/help.txt
- test/retest/options_test.rb
> Retest version option

- features/bundler-app/Dockerfile
- features/bundler-app/Gemfile.lock
- features/git-ruby/retest/support/output_file.rb
- features/hanami-app/retest/support/output_file.rb
- features/rails-app/retest/support/output_file.rb
- features/rspec-rails/retest/support/output_file.rb
- features/rspec-ruby/retest/support/output_file.rb
- features/ruby-app/retest/retest_test/matching_unmatching_command_test.rb
- features/ruby-app/retest/support/output_file.rb
- features/ruby-bare/retest/support/output_file.rb
- lib/retest/prompt.rb
- lib/retest/repository.rb
- test/retest/prompt_test.rb
- test/retest/repository/multiple_test_files_with_user_input.rb
- test/retest/repository_test.rb
> None skip option

- .github/workflows/ci.yml
- Gemfile.lock
- lib/retest/version.rb
Adding Ruby versions and reverting silly bundle version update.
> Add Ruby 3.2 and 3.3 to CI

- lib/retest/version_control/git.rb
> Diffs branch from Merge base instead of tip

- features/rspec-ruby/bin/retest
- features/rspec-ruby/retest/retest_test.rb
- features/rspec-ruby/retest/retest_test/interruptions.rb
- lib/retest/runner.rb
> Send TERM signal instead of INT when killing process

- exe/retest
- features/bundler-app/retest/retest_test/interactive_commands_test.rb
- lib/retest.rb
- lib/retest/matching_options.rb
- lib/retest/matching_options/path.rb
- lib/retest/output.rb
- lib/retest/program.rb
- lib/retest/repository.rb
- test/retest/matching_options/path_test.rb
- test/retest/matching_options_test.rb
- test/retest/output_test.rb
- test/retest/program_test.rb
- test/retest/repository_test.rb
- test/support/fixtures.rb
Fixes #267 
Proof of concept works. Things to consider before shipping
> Add Force batch option
